logging:
  file:
   name:
    File.log

spring:
  datasource:
    url: jdbc:h2:mem:db_movie
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
  sql:
    init:
      mode: always
  h2:
   console:
    enabled: true
    path: /h2-console
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
